package com.ouer.solar.location.server;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zone
 *
 * @mbggenerated
 */
public class Zone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.zip_code
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.creator_id
     *
     * @mbggenerated
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.archive
     *
     * @mbggenerated
     */
    private Byte archive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.id
     *
     * @return the value of zone.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.id
     *
     * @param id the value for zone.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.name
     *
     * @return the value of zone.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.name
     *
     * @param name the value for zone.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.zip_code
     *
     * @return the value of zone.zip_code
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.zip_code
     *
     * @param zipCode the value for zone.zip_code
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.path
     *
     * @return the value of zone.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.path
     *
     * @param path the value for zone.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.parent_id
     *
     * @return the value of zone.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.parent_id
     *
     * @param parentId the value for zone.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.creator_id
     *
     * @return the value of zone.creator_id
     *
     * @mbggenerated
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.creator_id
     *
     * @param creatorId the value for zone.creator_id
     *
     * @mbggenerated
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.archive
     *
     * @return the value of zone.archive
     *
     * @mbggenerated
     */
    public Byte getArchive() {
        return archive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.archive
     *
     * @param archive the value for zone.archive
     *
     * @mbggenerated
     */
    public void setArchive(Byte archive) {
        this.archive = archive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.created_at
     *
     * @return the value of zone.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.created_at
     *
     * @param createdAt the value for zone.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.updated_at
     *
     * @return the value of zone.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.updated_at
     *
     * @param updatedAt the value for zone.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}